name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Auto-assign to team
        uses: actions/github-script@v9
        with:
          script: |
            const assignees = ['Fahlevi20', 'rahmadyd'];
            const issueNumber = context.issue.number;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: assignees
            });
